
version: 2

models:
    - name: dim_channel
      description: "A starter dbt model"
      columns:
          - name: sales_channel_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: dim_channel_view_x
      description: "A starter dbt model"
      columns:
          - name: sales_channel_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
    - name: dim_garment_group
      description: "A starter dbt model"
      columns:
          - name: garment_group_no
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
name: fact_test
      description: "A starter dbt model"