
version: 2

models:
    - name: dim_channel
      description: "A starter dbt model"
      columns:
          - name: sales_channel_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null

    - name: dim_channel_view
      description: "A starter dbt model"
      columns:
          - name: sales_channel_id
            description: "The primary key for this table"
            tests:
                - unique
                - not_null
